name = "zwanski-cf-worker"
main = "src/index.js"
compatibility_date = "2024-12-01"

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

# Environment variables
vars = { ENVIRONMENT = "production" }
